openapi: 3.0.0
info:
  title: OpenAPI specification for the CycleStats API
  version: 1.0.2
servers:
  - url: /api/v1
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: query
    name: code    
  BearerAuth:
    type: http
    scheme: bearer        
paths:
  /summary:
    get:
      summary: Get summary information
      description: Returns summary about cyclist and rides
      operationId: getSummary
      security:
        - BearerAuth: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
  /statistics:
    get:
      summary: Get statistics
      description: Returns detailed statistics about cyclist and rides
      operationId: getStatistics
      security:
        - BearerAuth: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistics'
  /oauth/token:
    post:
      summary: Request OAuth 2.0 token
      description: Request an OAuth 2.0 token by providing an authorization code
      operationId: postToken
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          description: Authorization code used for requesting the OAuth 2.0 token
          required: true
          name: code
          type: string          
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  bearerToken:
                    type: string
components:
  schemas:
    Cyclist:
      description: Information about the cyclist
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string  
        sex:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        ftp:
          description: Functional threshold power in watts
          type: number
        weight:
          description: Weight in kilograms
          type: number
        profileUrl:
          type: string
        measurement:
          $ref: '#/components/schemas/MeasurementUnit'
        longestRide:
          type: number
        highestClimb:
          type: number
        bikes:
          type: array
          items:
            $ref: '#/components/schemas/Bike'
    Statistics:
      description: Detailed statistics about cyclist and rides
      type: object
      properties:
        monthlySummary:
          description: Riding statistics summarized for a given year and month
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Measurements'
              - type: object
                properties:
                  year:
                    type: number
                  months:
                    type: array
                    items:
                      $ref: '#/components/schemas/SummaryPerMonth'
                required:
                  - year
                  - months
        totalSummary:
          $ref: '#/components/schemas/Measurements'
      required:
        - monthlySummary
        - totalSummary
    Summary:
      description: Summary info about cyclist and rides
      type: object
      properties:
        cyclist:
          $ref: '#/components/schemas/Cyclist'
    SummaryPerMonth:
      allOf:
        - $ref: '#/components/schemas/Measurements'
        - type: object
          description: Summary of statistics on a monthly basis
          properties:
            month:
              description: Month of the year where 0 is January and 11 is December
              type: number
          required:
            - month
    MeasurementUnit:
      description: Indicates if imperial or metric units are used
      type: string
      enum:
        - IMPERIAL
        - METRIC
    Measurements:
      description: Different ride measurements
      type: object
      properties:
        distance:
          description: Distance in kilometers
          type: number
        elevation:
          description: Elevation gain in meters
          type: number
        rides:
          description: Number of rides
          type: number
        movingTime:
          description: Riding time in minutes
          type: number
        energy:
          description: Energy spent in kilowatt-hours
          type: number
    Bike:
      description: Details about a bicycle
      type: object
      properties:
        name:
          description: Make, model or name of the bicycle
          type: string
        distance:
          description: Distance ridden with the bicycle
          type: number
      required:
        - name
