openapi: 3.0.0
info:
  title: OpenAPI specification for the CycleStats API
  version: 1.0.2
servers:
  - url: /api/v1
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: query
    name: code    
  BearerAuth:
    type: http
    scheme: bearer        
paths:
  /summary:
    get:
      summary: Get summary information
      description: Returns summary about cyclist and rides
      operationId: getSummary
      security:
        - BearerAuth: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
  /statistics:
    get:
      summary: Get statistics
      description: Returns detailed statistics about cyclist and rides
      operationId: getStatistics
      security:
        - BearerAuth: []
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistics'
  /oauth/token:
    post:
      summary: Request OAuth 2.0 token
      description: Request an OAuth 2.0 token by providing an authorization code
      operationId: postToken
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          description: Authorization code used for requesting the OAuth 2.0 token
          required: true
          name: code
            type: string          
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  bearerToken:
                    type: string
components:
  schemas:
    Cyclist:
      description: Information about the cyclist
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string  
        sex:
          type: string
        location:
          type: string
        ftp:
          type: number
        weight:
          type: number
        profileUrl:
          type: string
        measurement:
          $ref: '#/components/schemas/MeasurementUnit'
    DistancePerMonth:
      description: Distance entry for a given month
      type: object
      properties:
        month:
          type: number
        year:
          type: number
        distance:
          type: number
      required:
        - month
        - year
        - distance
    Statistics:
      description: Detailed statistics about cyclist and rides
      type: object
      properties:
        distancesPerMonth:
          description: Distance ridden per month
          type: array
          items:
            $ref: '#/components/schemas/DistancePerMonth'
    Summary:
      description: Summary info about cyclist and rides
      type: object
      properties:
        cyclist:
          $ref: '#/components/schemas/Cyclist'
    MeasurementUnit:
      description: Indicates if imperial or metric units are used
      type: string
      enum:
        - IMPERIAL
        - METRIC
